[package]
name = "gipc"
version = "0.1.0"
authors = ["rickwebiii <rick.weber.iii@gmail.com>"]
edition = "2018"
path="src/lib.rs"

[dependencies]
grpcio = { version = "0.4.1", default-features = false, features = ["protobuf-codec"] }
named_pipe = "0.4.0"
