[package]
name = "gipc"
version = "0.1.0"
authors = ["rickwebiii <rick.weber.iii@gmail.com>"]
edition = "2018"
path="src/lib.rs"

[dependencies]
ipc = { Path = "../ipc" }
protobuf = "2.2.2"
futures-preview = "0.3.0-alpha.11"
