[package]
name = "gipc-examples"
version = "0.1.0"
authors = ["rickwebiii <rick.weber.iii@gmail.com>"]
edition = "2018"

[dependencies]
gipc = { path = "../gipc" }

[build-dependencies]
dirs = "1.0.4"