[package]
name = "gipc-examples"
version = "0.1.0"
authors = ["rickwebiii <rick.weber.iii@gmail.com>"]
edition = "2018"

[dependencies]
tools = { path = "../tools" }
grpcio = { path = "../gipc", package = "gipc" }
protobuf = "2.0.5"
futures = "0.1.25"

[build-dependencies]
dirs = "1.0.4"